name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Pre-build cleanup
      run: |
            rm -rf ./node-modules
            rm -f ./package-lock.json
            npm cache clean --force
    - name: Install Packages
      working-directory: ./client
      run: npm install
    - name: Build page
      working-directory: ./client
      run: CI=false npm run build
    - name: Copy build
      run: cp -r ./client/build ./api
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: "graphframejokubas@gmail.com"
        heroku_app_name: "saitynu-projektas"
        appdir: "api"
      env:
        MONGO_USR: ${{secrets.MONGO_USR}}
        MONGO_PWD: ${{secrets.MONGO_PWD}}
        MONGO_HOST: ${{secrets.MONGO_HOST}}
        MONGO_DBNAME: ${{secrets.MONGO_DBNAME}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        ACCESS_EXPIRATION: ${{secrets.ACCESS_EXPIRATION}}
        REFRESH_EXPIRATION: ${{secrets.REFRESH_EXPIRATION}}
